apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oradbauto
  labels:
    app: apexords-operator
    name: oradbauto
spec:
  selector:
     matchLabels:
        name: oradbauto-db-service
  serviceName: oradbauto-db-svc
  replicas: 1
  template:
    metadata:
        labels:
           name: oradbauto-db-service
    spec:
      securityContext:
         runAsUser: 54321
         fsGroup: 54321
      containers:
        - image: phx.ocir.io/idghdmhafadh/oit-sre-oke-admin/database:19.5
          imagePullPolicy: Always
          name: oradbauto
          ports:
            - containerPort: 1521
              name: oradbauto
          volumeMounts:
            - mountPath: /opt/oracle/oradata
              name: oradbauto-db-pv-oradata
            - mountPath: /opt/oracle/fra
              name: oradbauto-db-pv-fra
            - mountPath: /opt/oracle/diag
              name: oradbauto-db-pv-diag
          env:
            - name: ORACLE_SID
              value: "AUTOCDB"
            - name: ORACLE_PDB
              value: "AUTOPDB"
            - name:  ORACLE_PWD
              value: "changeit"
  volumeClaimTemplates:
  - metadata:
      name: oradbauto-db-pv-oradata
    spec:
      storageClassName: "oci-bv"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
  - metadata:
      name: oradbauto-db-pv-fra
    spec:
      storageClassName: "oci-bv"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
  - metadata:
      name: oradbauto-db-pv-diag
    spec:
      storageClassName: "oci-bv"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
